### ISSUE TITLE
What platforms do you need help on?

### ISSUE THREAD

**Issue by nicolasvahidzein** [kerimamansaryyev/dart_pusher_channels#14]
I have an app on ios and android, tell me how i can be of help?

**Comment by nicolasvahidzein** [comment]
I'm using laravel websockets on version 5.7.

**Comment by mcfugger** [comment]
Hello, I've update the README.md. I need to test it on `Linux` and `MacOS`

**Comment by kerimamansaryyev** [comment]
@SPiercer Hello, do you have any recent projects with Pusher Protocol? I would appreciate if you try to use the package on Linux platform. If you find any issues with the package - please, open a new issue. Make sure that your Pusher backend is upgraded to `ws` or `wss` schemes and supports the latest version of Pusher. If it runs, receives events without any problems - I will add Linux to supported platforms. Thank you in advance!

**Comment by SPiercer** [comment]
@kerimamansaryyev i do have a project but currently not in development however I'm here to help if we can hop into a call to test it out together

**Comment by kerimamansaryyev** [comment]
@SPiercer - Could you, please run the newest version (`1.0.0+6`) on MAC and LINUX machines using Flutter. Checkout the example project for credentials. They were derived from [test.pusher.com](https://test.pusher.com). Sorry for a late reply, I was a bit out with refactoring the package.

**Comment by kechankrisna** [comment]
> I'm using laravel websockets on version 5.7.

Found solution yet?

**Comment by kerimamansaryyev** [comment]
Closing this issue because the package is on the stable version and should work on all the platforms supported by Flutter. If any issue with compatibility appears - feel free to open it in a separate issue.
