### ISSUE TITLE
Error for private channels with + and emails

### ISSUE THREAD

**Issue by nicolasvahidzein** [kerimamansaryyev/dart_pusher_channels#21]
Hello,

i am still on vesion 0.3 but is it normal to have an error when I am trying to connect to a channel using the user's email like so:

private-user.nicolasemail@gmail.com

It fails all the time. Also it seems the backend (Laravel Websockets) does not like + signs in the channel name.

Any thoughts?

**Comment by kerimamansaryyev** [comment]
Hi, Nicolas! 
Please, enable logs like this:
```dart
PusherChannelsPackageConfigs.enableLogs();
```
And could you provide:
1. Logs of your events that come from Laravel Websockets.

**Comment by nicolasvahidzein** [comment]
ok, where do i paste this line?

**Comment by nicolasvahidzein** [comment]
I cannot authenticate when i use that channel name, i get a 403 error.

**Comment by kerimamansaryyev** [comment]
So, let's go step-by-step:

1. 

> ok, where do i paste this line?

In your main function, it will just print events to your console.

2. Provide the piece of code where you pass the authentication delegate into `client.privateChannel` method.

**Comment by nicolasvahidzein** [comment]
Ok here is the code:

```
			_channel ??= _pusher.privateChannel(
				defaultChannelName,
				TokenAuthorizationDelegate(
					authorizationEndpoint: Uri.parse(websocketsAuthEndpointDomain + websocketsAuthEndpointRelativeUrl),
					headers: {
						'Authorization':  'Bearer ' + accessToken,
						'Content-Type': 'application/json',
						'Accept': 'application/json'
					}
				)
			);
```
Logs enabled, where do i find the logs to attach please?

**Comment by kerimamansaryyev** [comment]
> Ok here is the code:
> 
> ```
> 			_channel ??= _pusher.privateChannel(
> 				defaultChannelName,
> 				TokenAuthorizationDelegate(
> 					authorizationEndpoint: Uri.parse(websocketsAuthEndpointDomain + websocketsAuthEndpointRelativeUrl),
> 					headers: {
> 						'Authorization':  'Bearer ' + accessToken,
> 						'Content-Type': 'application/json',
> 						'Accept': 'application/json'
> 					}
> 				)
> 			);
> ```
> 
> Logs enabled, where do i find the logs to attach please?

I think I know what's the issue. Please, remove 'Content-Type' header because the delegate provides `'content-type': 'application/x-www-form-urlencoded'`. Try removing it from the header and check if it helps.

**Comment by nicolasvahidzein** [comment]
Did not help sadly.

Where do i find the logs to send you?

**Comment by kerimamansaryyev** [comment]
What IDE do you use? You can find it in, for example, VS code terminal or VS code debug console.

**Comment by nicolasvahidzein** [comment]
Logs are not giving anything useful regarding the inability to connect. If you have more ideas let me know. I just stopped using emails for the channel name and used UUID instead. It is all peachy now. Let me know if should close this comment. Thank you kindly for all your help.

**Comment by kerimamansaryyev** [comment]
I've found the naming convention.
Here is it: https://pusher.com/docs/channels/using_channels/channels/#channel-naming-conventions.

It directly answers to the issue. Let me know if it was helpful.

**Comment by nicolasvahidzein** [comment]
private-user.nico@sodicopnr.com does not work sadly. But no big deal at this point. Just thought you should know.

**Comment by kerimamansaryyev** [comment]
> [private-user.nico@sodicopnr.com](mailto:private-user.nico@sodicopnr.com) does not work sadly. But no big deal at this point. Just thought you should know.

Just visit the link:
https://pusher.com/docs/channels/using_channels/channels/#channel-naming-conventions.

It says that @ symbol is not allowed in naming channels.

**Comment by nicolasvahidzein** [comment]
My sincere apologies, i was not reading that properly.

Much appreciated. I'm closing the ticket now.
