### ISSUE TITLE
Trigger not working with laravel-websockets

### ISSUE THREAD

**Issue by barees63** [kerimamansaryyev/dart_pusher_channels#24]
Hi there,

I'm trying to use this package to communicate with a laravel-websockets server.

I'm able to connect and subscribe to private and presence channels fine, if I send an event from the websockets dashboard the code receives it correctly. 

However trigger does nothing, no errors but nothing shows in the dashboard and other clients subscribed to the same private channel receive nothing.

I'm testing on both iOS and web and get the same behavior on both.

Does this ring a bell?

Thanks!

**Comment by kerimamansaryyev** [comment]
Hello, could you send your minimal code sample and logs that displayed on terminal (or Debug console) by this package? Enable logs calling `PusherChannelsPackageLogger.enableLogs()`

**Comment by kerimamansaryyev** [comment]
And also ensure that the pusher protocol version of your laravel-websockets support triggering the events

**Comment by kerimamansaryyev** [comment]
@barees63  Also be careful with what you try to send in `data`. You must send either objects of primitive types only (int, String, bool) or collections that contain only primitives:
```dart
 // Good
 myPresenceChannel.trigger(
    eventName: 'client-event',
    data: {'hello': 'Hello'},
  );

// Bad. Will fail
myPresenceChannel.trigger(
    eventName: 'client-event',
    data: MyClass(),
  );
```

**Comment by barees63** [comment]
this is the send function:

```
Future<void> sendMessage({required ChatMessage message}) async {
    final name =
        'private-${min(message.fromUserId, message.toUserId)}-${max(message.fromUserId, message.toUserId)}';
    final channel = _channels[name];
    if (channel == null) {
      debugPrint('Channel not found');
      return;
    }
    channel.trigger(
      eventName: 'message',
      data: jsonEncode({'hello': 'world'}), //message.toJson(),
    );
    }
```

and the logs:

```
flutter: Current lifecycle state: PusherChannelsClientLifeCycleState.pendingConnection
flutter: Timer was canceled
flutter: Received an event: {"event":"pusher:connection_established","data":"{\"socket_id\":\"565175652.31687435\",\"activity_timeout\":30}"}
flutter: Timer was canceled
flutter: Timer is set to: 0:02:00.000000
flutter: Current lifecycle state: PusherChannelsClientLifeCycleState.establishedConnection
flutter: Subscribed to presence channel presence-104
flutter: Subscribed to presence channel presence-40275
flutter: Subscribed to presence channel presence-224347
flutter: Received an event: {"event":"pusher_internal:subscription_succeeded","channel":"presence-104","data":"{\"presence\":{\"ids\":[0],\"hash\":[[]],\"count\":1}}"}
flutter: Got an event, continuing activity
flutter: Timer was canceled
flutter: Timer is set to: 0:02:00.000000
flutter: PresenceCubit: {"presence":{"ids":[0],"hash":[[]],"count":1}}
flutter: Received an event: {"event":"pusher_internal:subscription_succeeded","channel":"presence-40275","data":"{\"presence\":{\"ids\":[0],\"hash\":[[]],\"count\":1}}"}
flutter: Got an event, continuing activity
flutter: Timer was canceled
flutter: Timer is set to: 0:02:00.000000
flutter: PresenceCubit: {"presence":{"ids":[0],"hash":[[]],"count":1}}
flutter: Received an event: {"event":"pusher_internal:subscription_succeeded","channel":"presence-224347","data":"{\"presence\":{\"ids\":[0],\"hash\":[[]],\"count\":1}}"}
flutter: Got an event, continuing activity
flutter: Timer was canceled
flutter: Timer is set to: 0:02:00.000000
flutter: PresenceCubit: {"presence":{"ids":[0],"hash":[[]],"count":1}}
flutter: subscribed private-40275-120709
flutter: Received an event: {"event":"pusher_internal:subscription_succeeded","channel":"private-40275-120709"}
flutter: Got an event, continuing activity
flutter: Timer was canceled
flutter: Timer is set to: 0:02:00.000000
flutter: Attempt to trigger: {"event":"message","channel":"private-40275-120709","data":"{\"hello\":\"world\"}"}
```

laravel websockets has client messaging (?)  enabled:

```
'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => true,
            'enable_statistics' => true,
        ],
    ],
```

**Comment by barees63** [comment]
btw, if I pass a Map<String,dynamic> instead the encoded string it makes no difference.

> And also ensure that the pusher protocol version of your laravel-websockets support triggering the events

is that just the `enable_client_messages` setting or something else?

Thanks!

**Comment by kerimamansaryyev** [comment]
> btw, if I pass a Map<String,dynamic> instead the encoded string it makes no difference.
> 
> ```
> flutter: Attempt to trigger: {"event":"message","channel":"private-40275-120709","data":{"hello":"world"}}
> ```
> 
>  > And also ensure that the pusher protocol version of your laravel-websockets support triggering the events
> 
> is that just the `enable_client_messages` setting or something else?
> 
> Thanks!

I am not a server-side developer but there must be something missing on the server side. Maybe some filter blocks the client events. For example, maybe, client events with specific name can only be triggered. Try logging the messages that come to your server

**Comment by barees63** [comment]
ok, I'll keep battling :)

fwiw, the triggered message does make it to the server but it doesn't progagate, this is a log from laravel:

```
1194738: connection id 34846611.56071607 received message: {"event":"message","channel":"private-40275-120709","data":{"hello":"world"}}.
```

**Comment by kerimamansaryyev** [comment]
> ok, I'll keep battling :)
> 
> fwiw, the triggered message does make it to the server but it doesn't progagate, this is a log from laravel:
> 
> ```
> 1194738: connection id 34846611.56071607 received message: {"event":"message","channel":"private-40275-120709","data":{"hello":"world"}}.
> ```
> 
> So I'd say you're quite correct, back end issue.

If you make it through in backend - please, leave a comment with a solution. It may help others who will visit the issues. I will keep it open until you resolve it. Thank you in advance!

**Comment by barees63** [comment]
I will, and thank you for a very nice package, I always prefer pure dart.

**Comment by barees63** [comment]
so sorry to have bothered you with this!  It was just me.. I didn't realize I needed to prefix the event name with `client-` for client messaging.  It's now working perfectly, thanks.

**Comment by mehmetgultekin** [comment]
@barees63 i'm having same problem. could you write how did you do on server side?

"beyondcode/laravel-websockets": "^1.13",
"pusher/pusher-php-server": "^7.0"
