### ISSUE TITLE
Reset auth token?

### ISSUE THREAD

**Issue by Aerofluxx** [kerimamansaryyev/dart_pusher_channels#29]
Hey :)

First of all thank you so much for this package!

What I'm trying todo is, that I want to remove the "stored" auth:token from the cache.

In my case, I've a logout for my user, calling:

    userChannel?.unsubscribe();
    client.disconnect();

After logging into the app again, the userChannel still try to login with the previous "stored" auth:token instead of requesting a new auth:token.

So, is there a way to simply remove a stored auth:token of a channel?
Thank you so much!
mike

**Comment by kerimamansaryyev** [comment]
@Aerofluxx Hi! Try to just recreate the channel adding `forceCreateNewInstance:true` so it will recreate the object inside the internal map of channels:
```dart
PrivateChannel myPrivateChannel = client.privateChannel(
    'private-channel',
    authorizationDelegate:
        EndpointAuthorizableChannelTokenAuthorizationDelegate.forPrivateChannel(
      authorizationEndpoint: Uri.parse('https://test.pusher.com/pusher/auth'),
      headers: const {},
    ),
    forceCreateNewInstance: true,
  );
```

**Comment by Aerofluxx** [comment]
After looking over hours ... overlooking this parameter, I almost feel ashamed.

Thank you so much for your super quick answer. :) Works perfectly!

**Comment by kerimamansaryyev** [comment]
@Aerofluxx You are welcome! Feel free to close the issue if it works.
