### ISSUE TITLE
Private Event is not subscribed to the server . when i send event i receive No event 

### ISSUE THREAD

**Issue by mimoislam** [kerimamansaryyev/dart_pusher_channels#32]
I/flutter (27787): Received an event: {"event":"pusher_internal:subscription_succeeded","channel":"private-client.51"}
I/flutter (27787): Got an event, continuing activity
I/flutter (27787): Timer was canceled
I/flutter (27787): Timer is set to: 0:00:30.000000
I/flutter (27787): Attempt to trigger: {"event":"client-event","channel":"private-client.51","data":{"hello":"Hello"}}
I/flutter (27787): Received an event: {"event":"pusher:error","channel":"private-client.51","data":{"code":4301,"message":"The app does not have client messaging enabled."}}

and every time i connect to my private connection it do this
Received an event: {"event":"pusher_internal:subscription_succeeded","channel":"private-client.51"}
but without my event name

**Comment by kerimamansaryyev** [comment]
@mimoislam and how shall I understand what is the problem? Format the issue. 
1. What you need?
2. What is the issue achieving this
3. Piece of code in a formatted form.

**Comment by kerimamansaryyev** [comment]
@mimoislam  As far as I understood, here is the reason why your code does not work:
Your logs literally tell you:
```
{"event":"pusher:error","channel":"private-client.51","data":{"code":4301,"message":"The app does not have client messaging enabled."}}
```
Did you read it ? Your server does not support sending client messages.

**Comment by mimoislam** [comment]
> @mimoislam and how shall I understand what is the problem? Format the issue.
> 
> 1. What you need?
> 2. What is the issue achieving this
> 3. Piece of code in a formatted form.


 1. firstly when i make  connection with our custom server   there is ping pong but when sending a event from server i do not receive  anything  even when i connect to my private channel 
 2. No Event Received Even when i connected to  the event .
 3. Does it connect to the event directly App\Events\V1\Event or  do i need to add the name of the event i did both but no event received
4.code Example :   `
             PusherChannelsPackageLogger.enableLogs();
                // Create an instance PusherChannelsOptions
                // The test options can be accessed from test.pusher.com (using only for test purposes)
                const testOptions = PusherChannelsOptions.fromHost(
                  scheme: 'ws',
                  host: EVENT_URL,
                  key: PUSHER_KEY,
                  port: 6002,
                );
                print(testOptions.uri.toString());
          
                // Create an instance of PusherChannelsClient
                 client = PusherChannelsClient.websocket(
                  options: testOptions,
          
                  // Connection exceptions are handled here
                  connectionErrorHandler: (exception, trace, refresh) async {
          
                    print("exception1");
                    print(exception);
                    print(trace);
                    // This method allows you to reconnect if any error is occurred.
                  },
                );
          
          
          
                 myPrivateChannel = client.privateChannel(
                  "private-client.$idClient",
          
                  authorizationDelegate:
                  EndpointAuthorizableChannelTokenAuthorizationDelegate.forPrivateChannel(
                    authorizationEndpoint: Uri.parse(AUTH_URL),
                    onAuthFailed: (exception, trace) {
                      print("exception1");
                      print(exception);
                      print(trace);
                      },
          
                    headers:  {
                      'Authorization': 'Bearer $token',
                    },
                  ),
                );
           myPrivateChannel.bind("Event1").listen((event) {
                  print('Event from the private channel fired!');
                });
             client.onConnectionEstablished.listen((_) {
                  print("onConnectionEstablished");
          
                });
                unawaited(client.connect()) ;
`

**Comment by kerimamansaryyev** [comment]
@mimoislam How the client library will understand that `Event1`  is `App\Events\V1\Event`? Of course, you must type the exact event name

**Comment by kerimamansaryyev** [comment]
The problem may have been on the server side. Was resolved in a call with @mimoislam

**Comment by Shahmirzali-Huseynov** [comment]
@mimoislam Do you remember how solved your issue?
