### ISSUE TITLE
extension shortcuts

### ISSUE THREAD

**Issue by ondanplatform** [kerimamansaryyev/dart_pusher_channels#34]
We have to do ourself or ? if yes can you give one example ? 

<img width="833" alt="Screenshot 2023-08-26 at 01 00 55" src="https://github.com/kerimamansaryyev/dart_pusher_channels/assets/106958390/3308580c-bc88-4e1f-9001-c4a01e2b54fa">

**Comment by kerimamansaryyev** [comment]
It's worth checking the `Example` tab in pub.dev.
<img width="776" alt="Screenshot 2023-08-25 at 16 12 35" src="https://github.com/kerimamansaryyev/dart_pusher_channels/assets/73200585/0076c05a-50a6-41aa-bbad-9ead1736ac2f">
2.

**Comment by kerimamansaryyev** [comment]
@ondanplatform Has it solved your issue?

**Comment by ondanplatform** [comment]
it's for only presence channel ? cause I'm using private channel.

**Comment by kerimamansaryyev** [comment]
> it's for only presence channel ? cause I'm using private channel.

I’ve got your point, I should encapsulate the methods. Well, the extension method shown above can be applicable logically only for presence channels

**Comment by kerimamansaryyev** [comment]
Fixed with #35 . The version `1.1.1` is now available on pub.dev. Did it solve the issue?

**Comment by ondanplatform** [comment]
okay I thought these methods are available for private Channel too.
