### ISSUE TITLE
How to use this with laravel_echo?

### ISSUE THREAD

**Issue by HadiHassan22** [kerimamansaryyev/dart_pusher_channels#36]
Hello, I'm trying to use this package with laravel_echo, however what's confusing me is that this package requires you to define your authorization delegate while creating a private channel, but with the echo library you connect to private channels completely separate. Am I missing something?

**Comment by HadiHassan22** [comment]
@nicolasvahidzein It seems that you got both of these packages working together so if you could help with this issue your assistance would be greatly appreciated.

**Comment by nicolasvahidzein** [comment]
Can you contact me on skype so i can guide you? Nzein19

**Comment by kerimamansaryyev** [comment]
Long time no news, so I will close it. Feel free to reopen if needed
