### ISSUE TITLE
upgrade: requesting for updating the http dependency version.

### ISSUE THREAD

**Issue by iamriajul** [kerimamansaryyev/dart_pusher_channels#37]
Currently, the official `http` package version is `http: ^1.1.0`
I think we should updating this package to use latest version of `http` package.

Recently I've also got some issues when trying to install some latest package, some latest packages are required to have `http: ^1.0.0` because of this version resolution conflict I couldn't install those packages.

Thanks for making such a good package.

**Comment by kerimamansaryyev** [comment]
@iamriajul Thank you for mentioning this! I will do it today later.

**Comment by kerimamansaryyev** [comment]
@iamriajul Fixed, checkout int [1.2.1](https://pub.dev/packages/dart_pusher_channels/changelog). Has it solved your issue?

**Comment by iamriajul** [comment]
Thanks for being so responsive.
I appreciate your efforts in making this package.

Thanks. the release has solved my issue.
