### ISSUE TITLE
websocketchannelexception handshake exception 

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [kerimamansaryyev/dart_pusher_channels#39]
I get this error when I use a hotspot internet connection. I mean, I have two phones. first phone sharing mobile data. ( in the first phone there is an error) but in the second phone which is using the internet(hotspot) from the first phone I get handshake error: 

`websocketchannelexception handshake exception connection terminated during handshake`

Device iPhone 8 real device.

I tested in Android. it's working, no problem.

**Comment by Shahmirzali-Huseynov** [comment]
by the way api requests are working

**Comment by kerimamansaryyev** [comment]
If it gives that exception, I believe it's not the issue of this package, maybe an issue with your connection since the package relies on the websocket_channels and http, nothing else regarding the connection
