### ISSUE TITLE
How to get  count subscription  in private channel ?

### ISSUE THREAD

**Issue by rawezhcode** [kerimamansaryyev/dart_pusher_channels#45]

**Comment by rawezhcode** [comment]
please??

**Comment by kerimamansaryyev** [comment]
@rawezhcode I don't fully understand what you are trying to achieve. By a rule, private channels are not presence channels, you can not see number of its subscribers

**Comment by rawezhcode** [comment]
@kerimamansaryyev  I asked that question to see if I could see the number of participants.
Because in one presence channel what I saw is that only 100 users can be subscribed?

**Comment by kerimamansaryyev** [comment]
@rawezhcode Private channels do not support that feature. If you want to do that for private channels - you need probably to implement manually on the server-side by adding subscribers number into payload. So it's not an issue or a responsibility of this package. So, is the issue resolved?
