### ISSUE TITLE
Pusher Client Connection Status

### ISSUE THREAD

**Issue by mahibul1073** [kerimamansaryyev/dart_pusher_channels#46]
How to check Pusher client connected or not.Here i found channel connection status but how to check pusher client are connected or not connected.

**Comment by kerimamansaryyev** [comment]
I apologize for a late reply, I will add it later into the docs:

Listen the stream upon an instance of `PusherChannelsClient`:
```dart
client.lifecycleStream.listen((PusherChannelsClientLifeCycleState event) {});
```
