### ISSUE TITLE
Method not found: 'UnmodifiableUint8ListView'.

### ISSUE THREAD

**Issue by lpickford-pixelbeard** [kerimamansaryyev/dart_pusher_channels#48]
The following breaking change means that the `pinenacl` dependency no longer compiles on Flutter `^3.24.0`

https://github.com/dart-lang/sdk/issues/45115

```
../../AppData/Local/Pub/Cache/hosted/pub.dev/pinenacl-0.5.1/lib/api/api.dart:90:12: Error: Method not found:
'UnmodifiableUint8ListView'.
    return UnmodifiableUint8ListView(Uint8List.fromList(data.toList()));
           ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by lpickford-pixelbeard** [comment]
Updating the `pinenacl` library to `^0.6.0` fixes this, though I'm unable to open a PR due to permissions.

**Comment by Kal-Elx** [comment]
For now we can override the dependency in `pubspec.yaml` but it would be nice if you can updated the  package @kerimamansaryyev.

```
dependency_overrides:
  pinenacl: 0.6.0
```

Thanks!

**Comment by lpickford-pixelbeard** [comment]
> For now we can override the dependency in `pubspec.yaml` but it would be nice if you can updated the package @kerimamansaryyev.
> 
> ```
> dependency_overrides:
>   pinenacl: 0.6.0
> ```
> 
> Thanks!

Yep this is what we've done for now :)

**Comment by kerimamansaryyev** [comment]
I will take care of this today

**Comment by kerimamansaryyev** [comment]
@lpickford-pixelbeard @Kal-Elx Try the version `1.2.3` of the package, it should be working fine now. Let me know if I can close the issue

**Comment by lpickford-pixelbeard** [comment]
Works for me, thanks! :)

**Comment by kerimamansaryyev** [comment]
> Works for me, thanks! :)

Glad to hear! I’m closing the issue
