### ISSUE TITLE
Can't get private channels to work with Laravel Reverb

### ISSUE THREAD

**Issue by juliansteenbakker** [kerimamansaryyev/dart_pusher_channels#50]
So i've tried to use this package with Laravel Reverb, and while public channels are working fine, i can't get authorization to work on private channels. I keep getting null on `$user`.

```php
Broadcast::channel('App.Models.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
```

I have setup the channel like this, and i've trippel checked if the headers are received correctly in Laravel. 

```dart
  late final myPrivateChannel = client.privateChannel(
    'App.Models.User.1',
    authorizationDelegate:
        EndpointAuthorizableChannelTokenAuthorizationDelegate.forPrivateChannel(
      authorizationEndpoint:
          Uri.parse('http://localhost:8000/broadcasting/auth'),
          onAuthFailed: (e, s) {
        debugPrint('AUTH FAILED $e, $s');
          },
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Authorization': 'Bearer ...',
          },
    ),
  );
```

**Comment by ahmic** [comment]
Try to replace Content-Type header with:

`'Content-Type': 'application/json',`

Additionaly if you are using Sanctum, add this above routes in channels.php config file

`Broadcast::routes(['middleware' => ['auth:sanctum']]);`

**Comment by juliansteenbakker** [comment]
I am using sanctum, and added `Broadcast::routes(['middleware' => ['auth:sanctum']]);`, however now i am getting a 403 unauthorized error.

I also tried it in Postman, where my own endpoint //api/users/own is returning my information, but changing it to /broadcast/auth results in the 403 unauthorized

**Comment by juliansteenbakker** [comment]
I got it working! Turns out that i had some wrong configuration in `bootstrap/app.php`. After i returned to laravel default, it started working!

```php
return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        api: __DIR__.'/../routes/api.php',
        commands: __DIR__.'/../routes/console.php',
        channels: __DIR__.'/../routes/channels.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        //
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
```
